version: 0.2

phases:
  pre_build:
    commands:
      - echo Connecting to Amazon ECR...
      - aws --version
      # - $(aws ecr get-login --region $AWS_DEFAULT_REGION --no-include-email)
      - aws ecr get-login-password --region ap-southeast-1 | docker login
        --username AWS --password-stdin
        633282583713.dkr.ecr.ap-southeast-1.amazonaws.com
      - REPOSITORY_URI=633282583713.dkr.ecr.ap-southeast-1.amazonaws.com/test
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=build-$(echo $CODEBUILD_BUILD_ID | awk -F":" '{print $2}')
  build:
    commands:
      - cd WebapiDemoDocker
      - docker build -t demoapi:latest .
      - docker tag demoapi:latest $REPOSITORY_URI:latest
  post_build:
    commands:
      - docker push $REPOSITORY_URI:latest